### PR TITLE
Add GA banner

### PR DESCRIPTION
**Pull request by MarkWoulfeNeo4j**
another one

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-402.surge.sh

Updated pages:
- [Welcome to Neo4j](https://neo4j-docs-getting-started-402.surge.sh/getting-started)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-402.surge.sh

Updated pages:
- [Welcome to Neo4j](https://neo4j-docs-getting-started-402.surge.sh/getting-started)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-getting-started-402.surge.sh

Updated pages:
- [Welcome to Neo4j](https://neo4j-docs-getting-started-402.surge.sh/getting-started)

**Comment by MarkWoulfeNeo4j** [comment]
@recrwplay should I be worried that the preview is still showing the ad on the sidebar even though I removed it in the second commit? I re-ran all the jobs but it's still there.

**Comment by recrwplay** [comment]
I don't see it - possibly you were viewing a cached version of the page

**Review by lidiazuin — APPROVED** [review]
Thank you Mark!! ✨

**Comment by MarkWoulfeNeo4j** [comment]
Cool, gone for me now too, merging

**Pull request merged**
